### PR TITLE
initial index.html

### PR DESCRIPTION
**Pull request by scottlehman**
initial index,html

### CODE REVIEW

**Review by AndrewJClement — APPROVED** [review]
Looks good!

**Review by kylekrny — APPROVED** [review]

**Review by kylekrny — APPROVED** [review]

**Review by kylekrny — APPROVED** [review]

**Review by dueckerr — APPROVED** [review]

**Review by AndrewJClement — APPROVED** [review]
Looks good!

**Review by dueckerr — APPROVED** [review]
Looks good

**Review by kylekrny — APPROVED** [review]

**Review by kylekrny — APPROVED** [review]

**Review by dueckerr — APPROVED** [review]
good

**Pull request merged**
